name: Build Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Helm
        uses: azure/setup-helm@v4
      
      - name: Package Helm Chart
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency build
          helm package .
      
      - name: Push Helm Chart
        run: |
          curl -u ${{ secrets.REPOSITORY_USER }}:${{ secrets.REPOSITORY_PASSWORD }} https://charts.repo.herrtxbias.net --upload-file *.tgz -v
